version: '3.8'

services:
  clinic_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: clinic-system-api:latest
    container_name: clinic_api
    ports:
      - "5000:8080"
    env_file:
      - ./Clinic-System.API/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./:/src

